import "./globals.css";

//Set the metadata for the page

export const metadata = {
  title: "CampusCast",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
